version: '3'

services:
  # ========================================
  # Serveur Mongo
  # ========================================
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      # Répertoire hôte: mongodata => Répertoire Container: /data/db
      - ./mongodata:/data/db
      - ./sample_datas:/root/sample_datas   # Répertoire pour récupérer dans le conteneur les jeux de données à importer
      - ./output_datas:/root/output_datas    # Répertoire pour sauvegarder les données via mongodump
    ports:
      # Partage du port 27017
      - 27017:27017
    command: [--auth]
    restart: always
    networks:
      - mongo-network

  # ========================================
  # Serveur Mongo Express (équivalent de PHPMyAdmin)
  # ========================================
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 808:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ROOT_USERNAME}:${ROOT_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo-network


  # Serveur Node 20
##  node:
##    # Si on souhaite utiliser une image toute prête
##    #image: node:latest
##
##    # Etant donné que l'on doit faire appel à npm install, il faut passer par un Dockerfile présent dans ./node_build
##    build:
##      context: .
##      dockerfile: ./node_build/Dockerfile
##
##    container_name: node
##    ports:
##      - 666:666
#    volumes:
#      # Liaison entre le dossier local et le dossier qui contiendra l'application node sur le container
#      - ./node_app:/app
#      - ./node_modules:/app/node_modules
#    working_dir: /app # Dossier de base dans lequel se placera ce container
#    #command: npm install -- npm run start

networks:
  mongo-network:
    driver: bridge
